// <auto-generated />
using System;
using Healthcare;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Healthcare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Healthcare.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 17, 9, 40, 2, 172, DateTimeKind.Utc).AddTicks(6138),
                            Name = "Dr. Alfabet",
                            UpdatedAt = new DateTime(2025, 12, 17, 9, 40, 2, 172, DateTimeKind.Utc).AddTicks(6266)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 17, 9, 40, 2, 172, DateTimeKind.Utc).AddTicks(6523),
                            Name = "Dr. Sarah Quinn",
                            UpdatedAt = new DateTime(2025, 12, 17, 9, 40, 2, 172, DateTimeKind.Utc).AddTicks(6524)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 17, 9, 40, 2, 172, DateTimeKind.Utc).AddTicks(6525),
                            Name = "Dr. Michael Jordan",
                            UpdatedAt = new DateTime(2025, 12, 17, 9, 40, 2, 172, DateTimeKind.Utc).AddTicks(6525)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 17, 9, 40, 2, 172, DateTimeKind.Utc).AddTicks(6526),
                            Name = "Dr. Kevin McCalister",
                            UpdatedAt = new DateTime(2025, 12, 17, 9, 40, 2, 172, DateTimeKind.Utc).AddTicks(6526)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 17, 9, 40, 2, 172, DateTimeKind.Utc).AddTicks(6527),
                            Name = "Dr. Medusa",
                            UpdatedAt = new DateTime(2025, 12, 17, 9, 40, 2, 172, DateTimeKind.Utc).AddTicks(6528)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
